eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  freemarker:
    prefer-file-system-access: false
  application:
    name: api-gateway
server:
  port: 9999

zuul:
  max:
    host:
      connections: 10000
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
  MaxTotalHttpConnections: 5000
  MaxConnectionsPerHost: 1000