server:
  port: ${SERVER_PORT:12305}

spring:
  application:
    name: pcmember-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
