server:
  port: ${SERVER_PORT:12803}

spring:
  application:
    name: article-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
